FROM mx-jdk8/oracle

RUN mkdir -p /app/log/manager
RUN touch /app/log/manager/mx-manager

WORKDIR /app

COPY ./target/mx-module-manager-biz-1.0-SNAPSHOT.jar /app/cloud-manager.jar

ENV LANG=en_US.UTF8
ENV TZ=Asia/Shanghai

EXPOSE 8205