server:
  port: 9990
  devtools:
    restart:
      enabled: true



spring:
  application:
    name: cloud-manager

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848 # nacos 地址和端口
        file-extension: yaml # 获取配置文件的格式：yaml
        username: 127.0.0.1 # nacos 认证用户名
        password: 127.0.0.1 # nacos 认证密码
  boot:
    admin:
      client:
        # 服务端 url
        url: http://127.0.0.1:9999
        instance:
          # 客户端实例 url
          service-url: http://127.0.0.1:9990
          prefer-ip: true
          # 客户端实例名称
          name: cloud-manager
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud-manage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: ab215687DA.
      initial-size: 5 # 初始化连接大小
      max-active: 20 # 最大连接池数量
      min-idle: 5 # 最小连接池数量
      max-wait: 60000 # 获取连接时最大等待时间，单位毫秒
      pool-prepared-statements: false # 是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      max-pool-prepared-statement-per-connection-size: 20 # 开启poolPreparedStatements后生效
      time-between-eviction-runs-millis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 600000 # 配置一个连接在池中最小生存的时间，单位是毫秒,必须比配置大最小值大
      validation-query: SELECT 1 FROM DUAL # 测试连接
      # validation-query-timeout: 5000
      test-on-borrow: false # 获取连接时执行检测，建议关闭，影响性能
      test-on-return: false # 归还连接时执行检测，建议关闭，影响性能
      test-while-idle: true # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能;慢SQL记录
      filters: stat,wall # 配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/* # druid监控页面，账号和密码都在配置类代码中配置


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration: #开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback.xml


management:
  endpoints:
    web:
      exposure:
        # 暴漏的接口 - 所有接口
        include: "*"
mx:
  logstash:
    enable: false
    address: 127.0.0.1:5000
    name: ts
